cifra/urls.py
from django.conf.urls import patterns, url
from cifra import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
#     url(r'^perfis/(?P<perfil_id>\d+)$', views.exibir, name='exibir'),
#     url(r'^perfis/(?P<perfil_id>\d+)/convidar$', views.convidar, name='convidar')
#         url(r'^perfis/(?P<perfil_id>\d+)$', 'perfis.views.perfis')
    
)

hello/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('perfis.urls')),
    url(r'^', include('usuarios.urls')),
#     url(r'^', include('cifra.urls'))
)

perfis/urls.py
from django.conf.urls import patterns, url
from perfis import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^perfis/(?P<perfil_id>\d+)$', views.exibir, name='exibir'),
    url(r'^perfis/(?P<perfil_id>\d+)/convidar$', views.convidar, name='convidar'),
    url(r'^convite/(?P<convite_id>\d+)/aceitar$', views.aceitar, name='aceitar')
#         url(r'^perfis/(?P<perfil_id>\d+)$', 'perfis.views.perfis')
    
)

usuarios/urls.py
from django.conf.urls import patterns, url, include
from usuarios.views import RegistrarUsuarioView

urlpatterns = patterns('',
    url(r'^registrar/$',RegistrarUsuarioView.as_view(), name="registrar")
)

cifra/models.py
# from django.db import models
# 
# 
# class Perfil(models.Model):
#     nome = models.CharField(max_length=255, null=False)
#     telefone = models.CharField(max_length=255, null=False)
#     email = models.CharField(max_length=15, null=False)
#     nome_empresa = models.CharField(max_length=255, null=False)
#     
#     def convidar(self, perfil_convidado):
#        Convite(solicitante= self, convidado=perfil_convidado).save()
#     
# class Convite(models.Model):
#     solicitante = models.ForeignKey(Perfil, related_name='convites_feitos')
#     convidado = models.ForeignKey(Perfil, related_name='convites_recebidos')    

perfis/models.py
from django.db import models


class Perfil(models.Model):
    nome = models.CharField(max_length=255, null=False)
    telefone = models.CharField(max_length=255, null=False)
    email = models.CharField(max_length=15, null=False)
    nome_empresa = models.CharField(max_length=255, null=False)
    amigos= models.ManyToManyField("self")
    
    def convidar(self, perfil_convidado):
       Convite(solicitante= self, convidado=perfil_convidado).save()
    
class Convite(models.Model):
    solicitante = models.ForeignKey(Perfil, related_name='convites_feitos')
    convidado = models.ForeignKey(Perfil, related_name='convites_recebidos') 

    def aceitar(self):
        self.convidado.amigos.add(self.solicitante)
        self.solicitante.amigos.add(self.convidado)
        self.delete()
        

usuarios/models.py
from django.db import models

# Create your models here.

cifra/views.py
from django.shortcuts import render,redirect
# from perfis.models import Perfil

def index (request):
    return render(request, 'index.html')
# def exibir(request, perfil_id):
#     perfil = Perfil.objects.get(id=perfil_id)
#     if perfil is None:
#         print('Entrei aqui')
#         perfil = Perfil()
#         
#     return render(request, 'perfis.html', {'perfil': perfil, 'perfil_logado': get_perfil_logado(request)})
# 
# def convidar(request, perfil_id):
#     perfil_convidado = Perfil.objects.get(id=perfil_id)
#     perfil_logado = get_perfil_logado(request)
#     perfil_logado.convidar(perfil_convidado)
#     return redirect('index')
#     
# 
# def get_perfil_logado(request):
#     return Perfil.objects.get(id=1)

perfis/views.py
from django.shortcuts import render,redirect
from perfis.models import Perfil,Convite

def index (request):
    return render(request, 'index.html', {'perfis': Perfil.objects.all(), 'perfil_logado': get_perfil_logado(request)})
def exibir(request, perfil_id):
    perfil = Perfil.objects.get(id=perfil_id)
    if perfil is None:
        print('Entrei aqui')
        perfil = Perfil()
        
    return render(request, 'perfis.html', {'perfil': perfil, 'perfil_logado': get_perfil_logado(request)})

def convidar(request, perfil_id):
    perfil_convidado = Perfil.objects.get(id=perfil_id)
    perfil_logado = get_perfil_logado(request)
    perfil_logado.convidar(perfil_convidado)
    return redirect('index')

def aceitar(request, convite_id):
    convite_a_aceitar = Convite.objects.get(id=convite_id)
    convite_a_aceitar.aceitar()
    return redirect('index')

def get_perfil_logado(request):
    return Perfil.objects.get(id=1)

usuarios/views.py
from django.shortcuts import render
from django.views.generic.base import View

# Create your views here.
class RegistrarUsuarioView(View):
    
    template_name = 'registrar.html'

    def get(self, request):
        print('Entrei aqui dois')
        return render(request, self.template_name)
    def post(self, request):
        print('Entrei aqui 1')
        return render(request, self.template_name)

cifra/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="pt">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'style/css/bootstrap.css'%}">
    <link rel="stylesheet" href="{% static 'style/css/main.css'%}">
    <title>{% block title %} {% endblock title %}</title>
</head>

<body>

    <div class="container">
        <div class="header sticky-top">
            <ul class="nav nav-pills float-right">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'index' %}">{{perfil_logado.nome}}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Logout</a>
                </li>
            </ul>
            <h3 class="text-muted">ConnectedIn</h3>
        </div>
        <div class="row content">
            {% block body %}
            {% endblock %}
        </div>
    </div>
    <script src="{% static 'style/js/bootstrap.js' %}"></script>
</body>

</html>

cifra/templates/perfis.html
{% extends "base.html" %}
{% block title %}
Perfil
{% endblock title %}
{% block body %}
<div class="col-lg-12">
		<div class="text-center espaco">
			<h1>Informações sobre o Perfil</h1>
			<h2>{{perfil.nome}}</h2>
		</div>
		<table class="table">
			<thead>
				<tr>
					<th>Nome</th>
					<th>Email</th>
					<th>Telefone</th>
					<th>Empresa</th>
					<th>Ação</th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<td>{{perfil.nome}}</td>
					<td>{{perfil.email}}</td>
					<td>{{perfil.telefone}}</td>
					<td>{{perfil.nome_empresa}}</td>
					<td>
					<a class="btn btn-outline-primary" href="{% url 'index'%}">Voltar</a>
					<a class="btn btn-outline-primary" href="{% url 'convidar' perfil.id %}">Convidar</a></td>
				</tr>
			</tbody>
		</table>
		</div>
{% endblock body %}

perfis/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="pt">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'style/css/bootstrap.css'%}">
    <link rel="stylesheet" href="{% static 'style/css/main.css'%}">
    <title>{% block title %} {% endblock title %}</title>
</head>

<body>

    <div class="container">
        <div class="header sticky-top">
            <ul class="nav nav-pills float-right">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'index' %}">Nome</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Logout</a>
                </li>
            </ul>
            <h3 class="text-muted">ConnectedIn</h3>
        </div>
        <div class="row content">
            {% block body %}
            {% endblock %}
        </div>
    </div>
    <script src="{% static 'style/js/bootstrap.js' %}"></script>
</body>

</html>

perfis/templates/index.html
{% extends "base.html" %}
{% block title %}
Index
{% endblock title %}
{% block body %}
<div class="col-lg-12">
	<div class="espaco">
		<h1 class="text-center">Minha lista de Perfis</h1>
	</div>
	{% if perfis %}
	<table class="table">
		<thead>
			<tr>
				<th>Nome</th>
				<th>Email</th>
			</tr>
		</thead>
		<tbody>
			{% for perfil in perfis %}
			<tr onclick="javascript:location.href='{% url 'exibir' perfil.id %}'">
				<td>{{perfil.nome}}</td>
				<td>{{perfil.email}}</td>
			</tr>
			{% endfor %}

		</tbody>
	</table>
	{% else %}
	<p>Nenhum perfil encontrado</p>
	{% endif%}
	{% with total_convites=perfil_logado.convites_recebidos.count %}
	{% if total_convites %}
	<div class="card">
		<div class="card-header">
			Você tem {{total_convites}} Convite{{total_convites|pluralize}}
		</div>
		<div class="card-body">
			<ul class="list-group list-group-flush">
				{% for convite in perfil_logado.convites_recebidos.all %}
					<li class="list-group-item">
						<strong onclick="javascript:location.href='{% url 'exibir' convite.solicitante.id%}'">{{convite.solicitante.nome}}</strong>
						<a class="btn btn-outline-primary float-right" href="{% url 'aceitar' convite.id %}">Aceitar</a></td>
					</li>
				{% endfor %}
			</ul>

		</div>
	</div>
	{% else %}
	<div class="card espaco">
		<div class="card-body ">
			<p>Nenhum convite recebido :(</p>
		</div>
	</div>
	{% endif %}
	{% endwith %}

	<!-- Amigos -->
	{% with total_amigos=perfil_logado.amigos.count %}
	{% if total_amigos %}
	<div class="card espaco">
		<div class="card-header">
			Você tem {{total_amigos}} Amigo{{total_amigos|pluralize}}
		</div>
		<div class="card-body">
			<ul class="list-group list-group-flush">
				{% for amigo in perfil_logado.amigos.all %}
					<li class="list-group-item">
						<strong onclick="javascript:location.href='{% url 'exibir' amigo.id%}'">{{amigo.nome}}</strong>
					</li>
				{% endfor %}
			</ul>

		</div>
	</div>
	{% else %}
	<div class="card espaco">
		<div class="card-body ">
			<p>Nenhum convite recebido :(</p>
		</div>
	</div>
	{% endif %}
	{% endwith %}

</div>
{% endblock body %}

perfis/templates/perfis.html
{% extends "base.html" %}
{% block title %}
Perfil
{% endblock title %}
{% block body %}
<div class="col-lg-12">
		<div class="text-center espaco">
			<h1>Informações sobre o Perfil</h1>
			<h2>{{perfil.nome}}</h2>
		</div>
		<table class="table">
			<thead>
				<tr>
					<th>Nome</th>
					<th>Email</th>
					<th>Telefone</th>
					<th>Empresa</th>
					<th>Ação</th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<td>{{perfil.nome}}</td>
					<td>{{perfil.email}}</td>
					<td>{{perfil.telefone}}</td>
					<td>{{perfil.nome_empresa}}</td>
					<td>
					<a class="btn btn-outline-primary" href="{% url 'index'%}">Voltar</a>
					
					<a class="btn btn-outline-primary" href="{% url 'convidar' perfil.id %}" aria-disabled="true">Convidar</a></td>
				</tr>
			</tbody>
		</table>
		</div>
{% endblock body %}

usuarios/templates/base_usuario.html
{%load staticfiles%}

<!DOCTYPE html>
<html lang="pt">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>ConnectedIn</title>
    <link rel="stylesheet" href="{% static 'style/css/bootstrap.css'%}">
    <link rel="stylesheet" href="{% static 'style/css/main.css'%}">
</head>
<body>
    {% block body %}
    
    {% endblock body %}
</body>
</html>

usuarios/templates/registrar.html
{% extends "base_usuario.html" %}
{% block body %}
<div class="container">
    <div class="col-sm-4 mx-auto">
        <h3 class="text-center espaco">Criar usuário</h3>
        <form action="{% url 'registrar' %}">
            {% csrf_token %}
        <div class="form-group">
            <input id="id_email" type="text" name="email" class="form-control" placeholder="Email *" autofocus autocomplete="email" required>
        </div>
        <div class="form-group">
            <input id="id_nome" type="text" class="form-control" placeholder="Nome" autocomplete="name" required >
        </div>
        <div class="form-group">
            <input id="id_senha" type="password" class="form-control" placeholder="Senha" required>
        </div>
        <hr />
        <div class="form-group">
            <input id="id_telefone" type="tel" class="form-control" placeholder="Telefone" autocomplete="telefone" required >
        </div>
        <div class="form-group">
            <input id="id_nome_empresa" type="text" class="form-control" placeholder="Empresa" required >
        </div>
        <hr/>
        <div class="form-group">
            <button class="btn btn-lg btn-primary btn-block" type="submit" value="Login">Registrar</button>
        </div>
    </form>
    </div>
</div>
{% endblock body %}